export enum WsEvents {
  BROADCAST_OPEN_CHANNELS = 'BROADCAST_OPEN_CHANNELS'
}

export enum WsMessageEvents {
  JOIN_CHANNEL = 'JOIN_CHANNEL',
  LEAVE_CHANNEL = 'LEAVE_CHANNEL',
  CHANNED_DELETED = 'CHANNEL_DELETED',
  HANDSHAKE = 'HANDSHAKE',
  PIECE_PLACED = 'PIECE_PLACED',
  VALIDATE_WIN_GAME = 'VALIDATE_WIN_GAME',
  VALIDATE_WIN_GAME_SUCCESS = 'VALIDATE_WIN_GAME_SUCCESS',
  SURRENDER = 'SURRENDER'
}
