const TYPES = {
  ESTABLISH_CONNECTION: 'ESTABLISH_CONNECTION',
  JOIN_CHANNEL: 'JOIN_CHANNEL',
  BROADCAST_OPEN_CHANNELS: 'BROADCAST_OPEN_CHANNELS',
  LEAVE_CHANNEL: 'LEAVE_CHANNEL'
}

module.exports = TYPES;
